name: C SDK CI
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  linux:
    name: CI Test On Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install -yqq libcunit1-dev libcunit1 libcurl4 libcurl4-openssl-dev build-essential cmake
      - name: Build
        run: |
          set -e
          cmake .
          make
      - name: Test
        env:
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_TEST_BUCKET: ${{ secrets.QINIU_TEST_BUCKET }}
          QINIU_TEST_BUCKET_DOMAIN: ${{ secrets.QINIU_TEST_BUCKET_DOMAIN }}
        run: |
          set -e
          cd tests
          make test
      - name: Code Coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
  macos:
    name: CI Test On macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install curl cmake make cunit
      - name: Build
        run: |
          set -e
          OPENSSL_ROOT_DIR="$(brew --prefix)/opt/openssl/" cmake .
          make
      - name: Test
        env:
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_TEST_BUCKET: ${{ secrets.QINIU_TEST_BUCKET }}
          QINIU_TEST_BUCKET_DOMAIN: ${{ secrets.QINIU_TEST_BUCKET_DOMAIN }}
        run: |
          set -e
          cd tests
          make test
  windows:
    name: CI Test On Windows
    runs-on: windows-latest
    env:
      buildDir: '${{ github.workspace }}/build/'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Visual Studio Dev cmds
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install vcpkg
        uses: lukka/run-vcpkg@main
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgArguments: 'sqlite3'
          vcpkgTriplet: 'x64-windows'
          vcpkgGitCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
      - name: Install curl
        run: |
          $VCPKG_ROOT/vcpkg install curl --triplet x64-windows
        shell: bash
      - name: Install openssl
        run: |
          $VCPKG_ROOT/vcpkg install openssl --triplet x64-windows
        shell: bash
      - name: Cmake
        uses: lukka/run-cmake@v3
        env:
          CURL_ROOT: '${{ github.workspace }}/vcpkg/packages/curl_x64-windows'
          OPENSSL_ROOT: '${{ github.workspace }}/vcpkg/packages/openssl_x64-windows'
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: '-G "NMake Makefiles"'
          buildDirectory: ${{ env.buildDir }}
